title = "Penta Global"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Work"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "Blog"
    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Service"
    url = "/service"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "/contact"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "/blog"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

 #date_format = "6 January 2006"
 date_format = "Mon, Jan 2, 2006"

  #home = "Home"

  [params.slider]
    enable = true
    title = "Penta Global"
    subtitle = "The Universal Blockchain Connector"

  [params.wrapper]
    enable = true
    title = "About"
    italic = "We are currently living in the Blockchain revolution. From the simpiliest tasks to industry disrupting applications, The Blockchain data structure is poised to revolutionize the modern world, and Penta is the next-gen platform to change everything."
    paragraph = "'Penta' or 'PNT', short for Penta Network, is a next generation blockchain platform for both public and private projects. Designed to be a premier platform for transferring value, and operating high-performance decentralized applications Penta will remove roadblocks and reshape the blockchain landscape. With an emphasis on contributing to the real economy, Penta's unique consensus algorithm (DSC) and its truly distributed network architecture is building the world’s most inclusive, equitable, and decentralized blockchain community."
  [params.blog]
    enable = true
    title = "Latest On Penta Global"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    content1 = "The Penta Network is designed to connect to a wide range of blockchain networks, existing digital networks and off-chain systems. Penta is first in providing a comprehensive solution to the blockchain interoperability problem."
    content2 = "At its core is a robust public blockchain infrastructure that supports a high-performance application platform. In the same way you download apps onto your smart device from an App Store, you will be able to access decentralized applications (DApps) to run on the Penta blockchain. Launching a Penta DApp will enable everyone to navigate digital networks as productive tools for the digital economy."
    content3 = "The mission of Penta is to become the “Universal Blockchain Connector” through unique, innovative technology and a commitment to building an inclusive and decentralized community connecting the world to blockchain technology."
    [params.feature.button]
      caption = "View Works"
      url = "/work"

  [params.call]
    enable = true
    title = "Technology Without Borders or Limits"
    paragraph = "With the capacity to transform how people, organizations, government and business transact. "

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "We are building an inclusive community."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
